version: "3.4"

services:
  django:
    build: .
    ports:
      - ${PUBLIC_API_PORT:-8000}:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - USE_DOCKER=true
